# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starcraftHistory', '0006_auto_20170228_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='current_league',
            field=models.ForeignKey(blank=True, db_column='Current_league', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='starcraftHistory.League'),
        ),
    ]
