# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcraftHistory', '0007_auto_20170302_1033'),
    ]

    operations = [
    #    migrations.AlterField(
    #        model_name='games',
    #        name='current_league',
    #        field=models.CharField(blank=True, db_column='Current_league', max_length=45, null=True),
    #    ),
    ]
