# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    #    ('starcraftHistory', '0008_auto_20170302_1035'),
        ('starcraftHistory', '0006_auto_20170228_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clans',
            fields=[
                ('idglobal', models.AutoField(db_column='idclans', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=45, null=True)),
                ('abbrev', models.CharField(blank=True, db_column='abbrev', max_length=45, null=True)),
                ('idclan', models.IntegerField(blank=True, db_column='idclan', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Clans',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='league',
            name='server',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
