# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcraftHistory', '0009_auto_20170304_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='ladderid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
