# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starcraftHistory', '0010_auto_20170304_0720'),
        ('starcraftHistory', '0008_auto_20170302_1035'),
    ]

    operations = [
    ]
