# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcraftHistory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='alternate_path',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
