# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starcraftHistory', '0002_players_alternate_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Global',
            fields=[
                ('idglobal', models.AutoField(db_column='idglobal', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=45, null=True)),
                ('value', models.CharField(blank=True, db_column='value', max_length=45, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'Global',
            },
        ),
        migrations.AddField(
            model_name='league',
            name='member_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='sigle',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='guessopid',
            field=models.ForeignKey(blank=True, db_column='GuessOpId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='games_as_op', to='starcraftHistory.Players'),
        ),
        migrations.AlterField(
            model_name='games',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='games_as_p', to='starcraftHistory.Players'),
        ),
    ]
