# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcraftHistory', '0003_auto_20170227_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='pwins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='total_season_games',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='twins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='zwins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='pwins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='total_career_games',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='total_season_games',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='twins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='zwins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
