# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcraftHistory', '0004_auto_20170228_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='rankedlosses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='rankedwins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
