# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcraftHistory', '0005_auto_20170228_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='rankedlosses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='rankedwins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
