# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starcraftHistory', '0007_auto_20170304_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='guessopgameid',
            field=models.ForeignKey(blank=True, db_column='GuessOpGameId', null=True, on_delete=django.db.models.deletion.CASCADE, to='starcraftHistory.Games'),
        ),
    ]
