# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starcraftHistory', '0008_auto_20170304_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='current_league',
            field=models.ForeignKey(blank=True, db_column='Current_league', max_length=45, null=True, on_delete=django.db.models.deletion.CASCADE, to='starcraftHistory.League'),
        ),
        migrations.AlterField(
            model_name='players',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='starcraftHistory.League'),
        ),
    ]
