# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcraftHistory', '0009_auto_20170309_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='progamer',
            name='aligulac',
            field=models.CharField(blank=True, db_column='aligulac', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='progamer',
            name='mainrace',
            field=models.CharField(blank=True, db_column='race', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='progamer',
            name='nationality',
            field=models.CharField(blank=True, db_column='nationality', max_length=45, null=True),
        ),
    ]
